-- Create STUDENTS table
CREATE TABLE STUDENTS (
    ROLL_NO VARCHAR(10) PRIMARY KEY,
    FULL_NAME VARCHAR(25) NOT NULL,
    CITY VARCHAR(25),
    MOBILE VARCHAR(10) UNIQUE CHECK (MOBILE ~ '^[0-9]{10}$'),
    GENDER CHAR(1) NOT NULL CHECK (GENDER IN ('M', 'F'))
);

-- Create SEM_SECTION table
CREATE TABLE SEM_SECTION (
    SEC_ID VARCHAR(5) PRIMARY KEY,
    SEMESTER INTEGER NOT NULL CHECK (SEMESTER BETWEEN 1 AND 8),
    SECTION CHAR(1) NOT NULL CHECK (SECTION IN ('A', 'B', 'C'))
);

-- Create CLASS_ENROLLMENT table
CREATE TABLE CLASS_ENROLLMENT (
    ROLL_NO VARCHAR(10),
    SEC_ID VARCHAR(5),
    PRIMARY KEY (ROLL_NO, SEC_ID),
    FOREIGN KEY (ROLL_NO) REFERENCES STUDENTS(ROLL_NO) ON DELETE CASCADE,
    FOREIGN KEY (SEC_ID) REFERENCES SEM_SECTION(SEC_ID) ON DELETE CASCADE
);

-- Create COURSES table
CREATE TABLE COURSES (
    COURSE_CODE VARCHAR(8) PRIMARY KEY,
    COURSE_TITLE VARCHAR(20) NOT NULL,
    SEMESTER INTEGER NOT NULL CHECK (SEMESTER BETWEEN 1 AND 8),
    CREDITS INTEGER NOT NULL CHECK (CREDITS BETWEEN 1 AND 5)
);

-- Create INTERNAL_MARKS table
CREATE TABLE INTERNAL_MARKS (
    ROLL_NO VARCHAR(10),
    COURSE_CODE VARCHAR(8),
    SEC_ID VARCHAR(5),
    TEST1 INTEGER CHECK (TEST1 BETWEEN 0 AND 25),
    TEST2 INTEGER CHECK (TEST2 BETWEEN 0 AND 25),
    TEST3 INTEGER CHECK (TEST3 BETWEEN 0 AND 25),
    FINAL_IA INTEGER CHECK (FINAL_IA BETWEEN 0 AND 25),
    PRIMARY KEY (ROLL_NO, COURSE_CODE, SEC_ID),
    FOREIGN KEY (ROLL_NO) REFERENCES STUDENTS(ROLL_NO) ON DELETE CASCADE,
    FOREIGN KEY (COURSE_CODE) REFERENCES COURSES(COURSE_CODE) ON DELETE CASCADE,
    FOREIGN KEY (SEC_ID) REFERENCES SEM_SECTION(SEC_ID) ON DELETE CASCADE
);
