-- Create STUDENTS table
CREATE TABLE STUDENTS (
    ROLL_NO VARCHAR(10) PRIMARY KEY,
    FULL_NAME VARCHAR(25),
    CITY VARCHAR(25),
    MOBILE VARCHAR(10),
    GENDER CHAR(1)
);

-- Create SEM_SECTION table
CREATE TABLE SEM_SECTION (
    SEC_ID VARCHAR(5) PRIMARY KEY,
    SEMESTER INTEGER,
    SECTION CHAR(1)
);

-- Create CLASS_ENROLLMENT table
CREATE TABLE CLASS_ENROLLMENT (
    ROLL_NO VARCHAR(10),
    SEC_ID VARCHAR(5),
    PRIMARY KEY (ROLL_NO, SEC_ID),
    FOREIGN KEY (ROLL_NO) REFERENCES STUDENTS(ROLL_NO),
    FOREIGN KEY (SEC_ID) REFERENCES SEM_SECTION(SEC_ID)
);

-- Create COURSES table
CREATE TABLE COURSES (
    COURSE_CODE VARCHAR(8) PRIMARY KEY,
    COURSE_TITLE VARCHAR(20),
    SEMESTER INTEGER,
    CREDITS INTEGER
);

-- Create INTERNAL_MARKS table
CREATE TABLE INTERNAL_MARKS (
    ROLL_NO VARCHAR(10),
    COURSE_CODE VARCHAR(8),
    SEC_ID VARCHAR(5),
    TEST1 INTEGER,
    TEST2 INTEGER,
    TEST3 INTEGER,
    FINAL_IA INTEGER,
    PRIMARY KEY (ROLL_NO, COURSE_CODE, SEC_ID),
    FOREIGN KEY (ROLL_NO) REFERENCES STUDENTS(ROLL_NO),
    FOREIGN KEY (COURSE_CODE) REFERENCES COURSES(COURSE_CODE),
    FOREIGN KEY (SEC_ID) REFERENCES SEM_SECTION(SEC_ID)
);
